# Copyright 2024 The HuggingFace Inc. team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Records a dataset. Actions for the robot can be either generated by teleoperation or by a policy.

Example:

```shell
lerobot-record \
    --robot.type=so100_follower \
    --robot.port=/dev/tty.usbmodem58760431541 \
    --robot.cameras="{laptop: {type: opencv, index_or_path: 0, width: 640, height: 480, fps: 30}}" \
    --robot.id=black \
    --dataset.repo_id=<my_username>/<my_dataset_name> \
    --dataset.num_episodes=2 \
    --dataset.single_task="Grab the cube" \
    --dataset.streaming_encoding=true \
    --dataset.encoder_threads=2 \
    --display_data=true
    # <- Optional: specify video codec (auto, h264, hevc, libsvtav1). Default is libsvtav1. \
    # --dataset.vcodec=h264 \
    # <- Teleop optional if you want to teleoperate to record or in between episodes with a policy \
    # --teleop.type=so100_leader \
    # --teleop.port=/dev/tty.usbmodem58760431551 \
    # --teleop.id=blue \
    # <- Policy optional if you want to record with a policy \
    # --policy.path=${HF_USER}/my_policy \
```

Example recording with bimanual so100:
```shell
lerobot-record \
  --robot.type=bi_so_follower \
  --robot.left_arm_config.port=/dev/tty.usbmodem5A460822851 \
  --robot.right_arm_config.port=/dev/tty.usbmodem5A460814411 \
  --robot.id=bimanual_follower \
  --robot.left_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 1, "width": 640, "height": 480, "fps": 30},
    top: {"type": "opencv", "index_or_path": 3, "width": 640, "height": 480, "fps": 30},
  }' --robot.right_arm_config.cameras='{
    wrist: {"type": "opencv", "index_or_path": 2, "width": 640, "height": 480, "fps": 30},
    front: {"type": "opencv", "index_or_path": 4, "width": 640, "height": 480, "fps": 30},
  }' \
  --teleop.type=bi_so_leader \
  --teleop.left_arm_config.port=/dev/tty.usbmodem5A460852721 \
  --teleop.right_arm_config.port=/dev/tty.usbmodem5A460819811 \
  --teleop.id=bimanual_leader \
  --display_data=true \
  --dataset.repo_id=${HF_USER}/bimanual-so-handover-cube \
  --dataset.num_episodes=25 \
  --dataset.single_task="Grab and handover the red cube to the other arm" \
  --dataset.streaming_encoding=true \
  # --dataset.vcodec=auto \
  --dataset.encoder_threads=2
```
"""

import logging
import os
import time
from dataclasses import asdict, dataclass, field
from pathlib import Path
from pprint import pformat
from typing import Any

import numpy as np
import torch

from lerobot.cameras import (  # noqa: F401
    CameraConfig,  # noqa: F401
)
from lerobot.cameras.opencv.configuration_opencv import OpenCVCameraConfig  # noqa: F401
from lerobot.cameras.reachy2_camera.configuration_reachy2_camera import Reachy2CameraConfig  # noqa: F401
from lerobot.cameras.realsense.configuration_realsense import RealSenseCameraConfig  # noqa: F401
from lerobot.cameras.zmq.configuration_zmq import ZMQCameraConfig  # noqa: F401
from lerobot.configs import parser
from lerobot.configs.policies import PreTrainedConfig
from lerobot.datasets.feature_utils import build_dataset_frame, combine_feature_dicts
from lerobot.datasets.image_writer import safe_stop_image_writer
from lerobot.datasets.lerobot_dataset import LeRobotDataset
from lerobot.datasets.pipeline_features import aggregate_pipeline_dataset_features, create_initial_features
from lerobot.datasets.video_utils import VideoEncodingManager
from lerobot.policies.factory import make_policy, make_pre_post_processors
from lerobot.policies.pretrained import PreTrainedPolicy
from lerobot.policies.rtc import ActionInterpolator
from lerobot.policies.utils import make_robot_action
from lerobot.processor import (
    PolicyAction,
    PolicyProcessorPipeline,
    RobotAction,
    RobotObservation,
    RobotProcessorPipeline,
    make_default_processors,
)
from lerobot.processor.rename_processor import rename_stats
from lerobot.robots import (  # noqa: F401
    Robot,
    RobotConfig,
    bi_openarm_follower,
    bi_so_follower,
    earthrover_mini_plus,
    hope_jr,
    koch_follower,
    make_robot_from_config,
    omx_follower,
    openarm_follower,
    reachy2,
    so_follower,
    unitree_g1 as unitree_g1_robot,
)
from lerobot.robots.bi_openarm_follower import (
    ActionSafetyChecker,
    ActionSafetyConfig,
    ActionSafetyViolation,
)
from lerobot.teleoperators import (  # noqa: F401
    Teleoperator,
    TeleoperatorConfig,
    bi_openarm_leader,
    bi_so_leader,
    homunculus,
    koch_leader,
    make_teleoperator_from_config,
    omx_leader,
    openarm_leader,
    openarm_mini,
    reachy2_teleoperator,
    so_leader,
    unitree_g1,
)
from lerobot.teleoperators.keyboard.teleop_keyboard import KeyboardTeleop
from lerobot.utils.constants import ACTION, OBS_STR
from lerobot.utils.control_utils import (
    init_keyboard_listener,
    is_headless,
    predict_action,
    sanity_check_dataset_name,
    sanity_check_dataset_robot_compatibility,
)
from lerobot.utils.device_utils import get_safe_torch_device
from lerobot.utils.import_utils import register_third_party_plugins
from lerobot.utils.robot_utils import precise_sleep
from lerobot.utils.utils import (
    init_logging,
    log_say,
)
from lerobot.utils.visualization_utils import init_rerun, log_rerun_data


@dataclass
class DatasetRecordConfig:
    # Dataset identifier. By convention it should match '{hf_username}/{dataset_name}' (e.g. `lerobot/test`).
    repo_id: str
    # A short but accurate description of the task performed during the recording (e.g. "Pick the Lego block and drop it in the box on the right.")
    single_task: str
    # Root directory where the dataset will be stored (e.g. 'dataset/path'). If None, defaults to $HF_LEROBOT_HOME/repo_id.
    root: str | Path | None = None
    # Limit the frames per second.
    fps: int = 30
    # Number of seconds for data recording for each episode.
    episode_time_s: int | float = 60
    # Number of seconds for resetting the environment after each episode.
    reset_time_s: int | float = 60
    # Number of episodes to record.
    num_episodes: int = 50
    # Encode frames in the dataset into video
    video: bool = True
    # Upload dataset to Hugging Face hub.
    push_to_hub: bool = True
    # Upload on private repository on the Hugging Face hub.
    private: bool = False
    # Add tags to your dataset on the hub.
    tags: list[str] | None = None
    # Number of subprocesses handling the saving of frames as PNG. Set to 0 to use threads only;
    # set to ≥1 to use subprocesses, each using threads to write images. The best number of processes
    # and threads depends on your system. We recommend 4 threads per camera with 0 processes.
    # If fps is unstable, adjust the thread count. If still unstable, try using 1 or more subprocesses.
    num_image_writer_processes: int = 0
    # Number of threads writing the frames as png images on disk, per camera.
    # Too many threads might cause unstable teleoperation fps due to main thread being blocked.
    # Not enough threads might cause low camera fps.
    num_image_writer_threads_per_camera: int = 4
    # Number of episodes to record before batch encoding videos
    # Set to 1 for immediate encoding (default behavior), or higher for batched encoding
    video_encoding_batch_size: int = 1
    # Video codec for encoding videos. Options: 'h264', 'hevc', 'libsvtav1', 'auto',
    # or hardware-specific: 'h264_videotoolbox', 'h264_nvenc', 'h264_vaapi', 'h264_qsv'.
    # Use 'auto' to auto-detect the best available hardware encoder.
    vcodec: str = "libsvtav1"
    # Enable streaming video encoding: encode frames in real-time during capture instead
    # of writing PNG images first. Makes save_episode() near-instant. More info in the documentation: https://huggingface.co/docs/lerobot/streaming_video_encoding
    streaming_encoding: bool = False
    # Maximum number of frames to buffer per camera when using streaming encoding.
    # ~1s buffer at 30fps. Provides backpressure if the encoder can't keep up.
    encoder_queue_maxsize: int = 30
    # Number of threads per encoder instance. None = auto (codec default).
    # Lower values reduce CPU usage, maps to 'lp' (via svtav1-params) for libsvtav1 and 'threads' for h264/hevc..
    encoder_threads: int | None = None
    # Rename map for the observation to override the image and state keys
    rename_map: dict[str, str] = field(default_factory=dict)

    def __post_init__(self):
        if self.single_task is None:
            raise ValueError("You need to provide a task as argument in `single_task`.")


@dataclass
class RecordConfig:
    robot: RobotConfig
    dataset: DatasetRecordConfig
    # Whether to control the robot with a teleoperator
    teleop: TeleoperatorConfig | None = None
    # Whether to control the robot with a policy
    policy: PreTrainedConfig | None = None
    # Display all cameras on screen
    display_data: bool = False
    # Display data on a remote Rerun server
    display_ip: str | None = None
    # Port of the remote Rerun server
    display_port: int | None = None
    # Whether to  display compressed images in Rerun
    display_compressed_images: bool = False
    # Use vocal synthesis to read events.
    play_sounds: bool = True
    # Resume recording on an existing dataset.
    resume: bool = False
    # Action interpolation multiplier for smoother policy control (1=off, 2=2x, 3=3x)
    # Only applies when using a policy (not teleop)
    interpolation_multiplier: int = 1
    # Before the very first policy episode, smoothly raise both arms along the
    # SparkJAX "lift spine" so the policy starts from the "arms up, table-cleared"
    # ready pose instead of from the rest pose the user happened to leave them in.
    # Only applies when (a) a policy is loaded AND (b) the robot is a
    # BiOpenArmFollower; ignored otherwise. See
    # `lerobot.robots.bi_openarm_follower.lift_arms.lift_arms_to_ready` for the
    # full motion description.
    lift_arms_before_policy: bool = False
    # Phase 0 ("go to zero pose"): slow soft-gain ramp from the current pose
    # to the LeRobot-canonical OpenArm zero pose (arms hanging straight,
    # grippers closed; all joints = 0 deg by construction of the
    # ``OpenArmFollower.calibrate`` procedure). Always runs FIRST so the
    # arms anchor at a known posture regardless of where they were left
    # after the previous session. Set to 0 only if you have manually
    # positioned the arms at the zero pose already.
    lift_arms_pre_zero_s: float = 3.0
    # Phase 1 ("pre-ramp"): soft-gain ramp from the default-hanging pose to
    # the start of the lift spine (LIFT_SPINE[0]). Mirrors SparkJAX's C++
    # ``Control::AdjustPosition`` smooth-move (~2.2s + buffer).
    lift_arms_pre_ramp_s: float = 3.0
    # Spine sweep duration (s). Bumped from SparkJAX's 1.5s to 1.7s after we
    # appended READY_POSE_RAD as the spine's 10th waypoint (1.7s / 9 segments
    # ~= SparkJAX's original 188 ms/segment pacing).
    lift_arms_spine_s: float = 1.7
    # Command rate (Hz) used during the raise (must match the follower's PD update budget).
    lift_arms_hz: float = 50.0
    # Hold time (s) at the final spine waypoint before handing control to the policy.
    lift_arms_hold_s: float = 0.5
    # Hard-abort safety gate for policy actions: rejects NaN/Inf, values outside
    # a wide sanity envelope, and per-step deltas larger than the configured
    # thresholds. Mirrors SparkJAX's ``_check_action_safety``. Only applies when
    # a policy is loaded (teleop is trusted). On violation: log error, send the
    # last good action as a hold frame, raise ``ActionSafetyViolation`` which
    # propagates up to the ``try/finally`` that disconnects the robot (and
    # disables torque by default). Defaults below match SparkJAX, converted to
    # degrees.
    action_safety_enabled: bool = False
    # 0.5 rad / step at 50 Hz, in degrees. Anything larger than this between
    # consecutive policy outputs is treated as a fault (chunk-swap glitch, bad
    # diffusion sample, RTC splice landing wrong, ...).
    action_safety_max_joint_delta_deg: float = 28.647889756541159
    # 1.0 rad / step for grippers, in degrees.
    action_safety_max_gripper_delta_deg: float = 57.29577951308232
    # Absolute-envelope sanity gate (|value| <= limit). Intentionally wider than
    # the follower's kinematic joint limits — those are enforced by send_action;
    # this catches unit confusions and NaN-survived integrators.
    action_safety_abs_joint_limit_deg: float = 200.0
    action_safety_abs_gripper_limit_deg: float = 300.0

    # Lightweight per-iteration profiling for the record_loop. When True, the
    # loop measures get_observation, predict_action, and send_action latencies
    # and logs a rolling summary every ``profile_log_period_s`` seconds (median
    # / p95 per phase + inference vs queue-pop classification). Adds ~3 timer
    # calls per iteration — overhead is negligible. Use this to figure out
    # whether a sub-target loop rate is caused by camera reads, policy
    # inference, or CAN write latency. Default off so production logs stay
    # clean.
    profile_loop: bool = False
    profile_log_period_s: float = 1.0
    # Dump per-joint observation/action/delta for the first N iterations of
    # every policy episode. Use to verify that the policy is commanding
    # reasonable positions immediately after lift_arms hands over control
    # (e.g. if arms "drop" right after lift, this tells you whether the
    # policy is commanding a downward move or whether it's a hardware issue).
    # 0 = disabled.
    debug_first_actions: int = 0
    # Complementary to ``debug_first_actions``: dump per-joint state/action
    # on every iteration where fresh policy inference just ran (detected via
    # predict time > 100 ms, the standard heuristic the profile_loop uses).
    # For chunk-based policies (pi0/pi05/ACT/...) this gives you one log
    # line per chunk - useful for spotting whether the model's *intent*
    # drifts over time (e.g. arms slowly moving down means each new chunk
    # commands a slightly lower target, even if individual chunks look
    # like "hold position"). Capped at N inferences so the log doesn't
    # explode. 0 = disabled.
    debug_log_each_inference: int = 0

    def __post_init__(self):
        # HACK: We parse again the cli args here to get the pretrained path if there was one.
        policy_path = parser.get_path_arg("policy")

        if policy_path:
            cli_overrides = parser.get_cli_overrides("policy")

            self.policy = PreTrainedConfig.from_pretrained(policy_path, cli_overrides=cli_overrides)
            self.policy.pretrained_path = policy_path

        if self.teleop is None and self.policy is None:
            raise ValueError("Choose a policy, a teleoperator or both to control the robot")

    @classmethod
    def __get_path_fields__(cls) -> list[str]:
        """This enables the parser to load config from the policy using `--policy.path=local/dir`"""
        return ["policy"]


""" --------------- record_loop() data flow --------------------------
       [ Robot ]
           V
     [ robot.get_observation() ] ---> raw_obs
           V
     [ robot_observation_processor ] ---> processed_obs
           V
     .-----( ACTION LOGIC )------------------.
     V                                       V
     [ From Teleoperator ]                   [ From Policy ]
     |                                       |
     |  [teleop.get_action] -> raw_action    |   [predict_action]
     |          |                            |          |
     |          V                            |          V
     | [teleop_action_processor]             |          |
     |          |                            |          |
     '---> processed_teleop_action           '---> processed_policy_action
     |                                       |
     '-------------------------.-------------'
                               V
                  [ robot_action_processor ] --> robot_action_to_send
                               V
                    [ robot.send_action() ] -- (Robot Executes)
                               V
                    ( Save to Dataset )
                               V
                  ( Rerun Log / Loop Wait )
"""


def _swap_arms(vec: np.ndarray) -> np.ndarray:
    """Swap the two 8-D arm blocks of an OpenArm 16-D state/action vector.

    The lerobot BiOpenArmFollower packs the wire vector **right-arm-first**
    ([right_j1..7, right_grip, left_j1..7, left_grip]) to match its teleoperator,
    but the openpi checkpoint (SparkJAX-trained) expects **left-arm-first**
    ([left..., right...]) — confirmed by the mirror-symmetric norm stats. This
    swaps between the two conventions (it is its own inverse). Works on a 1-D
    (16,) vector or a 2-D (T, 16) chunk (operates on the last axis).
    """
    out = np.asarray(vec).copy()
    out[..., :8], out[..., 8:] = np.asarray(vec)[..., 8:], np.asarray(vec)[..., :8]
    return out


class OpenPIServerPolicy:
    """Drive the robot live from an openpi (PyTorch) websocket policy server.

    This bypasses the local lerobot policy entirely: it takes the SAME live
    observation lerobot built (live camera frames + live joint state), formats
    it the way the openpi server expects, runs inference over the wire, and
    returns the next wire-format action for the robot. It is the decisive test
    for "openpi works on this rig but lerobot doesn't" — if the arms do the task
    when driven by the server through lerobot's own camera/state/IO path, the
    bug is isolated to the lerobot policy stack, not the hardware or cameras.

    Units: the OpenArm follower reads/writes JOINT angles in degrees and the
    gripper in its native unit, but the openpi checkpoint is trained in radians.
    So we convert joint dims deg->rad on the way in and rad->deg on the way out;
    grippers pass through untouched.

    Chunking: matches how openpi is meant to run — query the server for a full
    action chunk (``horizon`` steps), execute it open-loop, then re-query when
    the queue drains. Set the horizon server-side (the user runs the server with
    horizon=50).
    """

    def __init__(self, host: str, port: int, image_key_map: dict[str, str]):
        import sys as _sys
        from collections import deque

        _client_src = "/home/evaughan/sparkpack/openpi/packages/openpi-client/src"
        if _client_src not in _sys.path:
            _sys.path.insert(0, _client_src)
        from openpi_client.websocket_client_policy import WebsocketClientPolicy

        self._client = WebsocketClientPolicy(host=host, port=port)
        self._queue: deque[np.ndarray] = deque()
        self._image_key_map = image_key_map
        logging.info(
            "[openpi-live] connected to %s:%d (image map: %s)",
            host, port, image_key_map,
        )

    @staticmethod
    def _as_hwc_uint8(arr: np.ndarray) -> np.ndarray:
        arr = np.asarray(arr)
        if arr.ndim == 3 and arr.shape[0] == 3 and arr.shape[2] != 3:
            arr = arr.transpose(1, 2, 0)
        if arr.dtype != np.uint8:
            if float(arr.max()) <= 1.0:
                arr = arr * 255.0
            arr = arr.clip(0, 255).astype(np.uint8)
        return np.ascontiguousarray(arr)

    @staticmethod
    def _encode_jpeg_rgb(img_hwc_rgb: np.ndarray) -> bytes:
        import cv2

        bgr = cv2.cvtColor(img_hwc_rgb, cv2.COLOR_RGB2BGR)
        ok, jpg = cv2.imencode(".jpg", bgr, [cv2.IMWRITE_JPEG_QUALITY, 85])
        if not ok:
            raise RuntimeError("cv2.imencode failed")
        return jpg.tobytes()

    def _query_chunk(self, observation_frame: dict, task: str) -> None:
        # Wire vector is RIGHT-arm-first; the model expects LEFT-arm-first.
        state_wire = np.asarray(
            observation_frame["observation.state"], dtype=np.float32
        ).flatten()
        state_model = _swap_arms(state_wire)  # -> left-first (model layout)
        # ALL 16 dims (joints AND gripper) are Damiao motors read in degrees on
        # the lerobot wire; the openpi checkpoint is trained in radians (the
        # gripper too — recorded follower position is radians, no 2.58 leader
        # scale on the recorded values). So convert the whole vector deg->rad.
        state_rad = np.deg2rad(state_model)

        images = {}
        for lerobot_cam, server_cam in self._image_key_map.items():
            img = observation_frame.get(f"observation.images.{lerobot_cam}")
            if img is None:
                raise KeyError(f"observation missing camera '{lerobot_cam}'")
            images[server_cam] = self._encode_jpeg_rgb(self._as_hwc_uint8(img))

        obs = {"state": state_rad, "images": images, "prompt": task or ""}
        result = self._client.infer(obs)
        chunk_rad = np.asarray(result["actions"], dtype=np.float32)  # [T, 16] left-first, rad

        chunk_model = np.rad2deg(chunk_rad)  # all dims rad->deg (joints + gripper)
        chunk_wire = _swap_arms(chunk_model)  # left-first -> right-first (robot layout)
        self._queue.clear()
        for row in chunk_wire:
            self._queue.append(row)

    def predict(self, observation_frame: dict, task: str) -> torch.Tensor:
        """Return the next wire-format action as a (1, 16) tensor."""
        if not self._queue:
            self._query_chunk(observation_frame, task)
        action = self._queue.popleft()
        return torch.from_numpy(np.asarray(action, dtype=np.float32)).unsqueeze(0)

    @property
    def chunk_empty(self) -> bool:
        return not self._queue


@safe_stop_image_writer
def record_loop(
    robot: Robot,
    events: dict,
    fps: int,
    teleop_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs after teleop
    robot_action_processor: RobotProcessorPipeline[
        tuple[RobotAction, RobotObservation], RobotAction
    ],  # runs before robot
    robot_observation_processor: RobotProcessorPipeline[
        RobotObservation, RobotObservation
    ],  # runs after robot
    dataset: LeRobotDataset | None = None,
    teleop: Teleoperator | list[Teleoperator] | None = None,
    policy: PreTrainedPolicy | None = None,
    preprocessor: PolicyProcessorPipeline[dict[str, Any], dict[str, Any]] | None = None,
    postprocessor: PolicyProcessorPipeline[PolicyAction, PolicyAction] | None = None,
    control_time_s: int | None = None,
    single_task: str | None = None,
    display_data: bool = False,
    interpolator: ActionInterpolator | None = None,
    display_compressed_images: bool = False,
    action_safety: ActionSafetyChecker | None = None,
    profile_loop: bool = False,
    profile_log_period_s: float = 1.0,
    debug_first_actions: int = 0,
    debug_log_each_inference: int = 0,
):
    if dataset is not None and dataset.fps != fps:
        raise ValueError(f"The dataset fps should be equal to requested fps ({dataset.fps} != {fps}).")

    teleop_arm = teleop_keyboard = None
    if isinstance(teleop, list):
        teleop_keyboard = next((t for t in teleop if isinstance(t, KeyboardTeleop)), None)
        teleop_arm = next(
            (
                t
                for t in teleop
                if isinstance(
                    t,
                    (
                        so_leader.SO100Leader
                        | so_leader.SO101Leader
                        | koch_leader.KochLeader
                        | omx_leader.OmxLeader
                    ),
                )
            ),
            None,
        )

        if not (teleop_arm and teleop_keyboard and len(teleop) == 2 and robot.name == "lekiwi_client"):
            raise ValueError(
                "For multi-teleop, the list must contain exactly one KeyboardTeleop and one arm teleoperator. Currently only supported for LeKiwi robot."
            )

    # Reset policy and processor if they are provided
    if policy is not None and preprocessor is not None and postprocessor is not None:
        policy.reset()
        preprocessor.reset()
        postprocessor.reset()

    # Reset interpolator if provided
    if interpolator is not None:
        interpolator.reset()

    # Re-arm the action-safety guard so the per-step delta baseline is seeded
    # from the current robot state at the start of each episode rather than
    # from a stale last-action from a prior episode.
    if action_safety is not None and policy is not None:
        action_safety.reset()

    # Calculate control interval based on interpolation
    use_interpolation = interpolator is not None and interpolator.enabled and policy is not None
    control_interval = interpolator.get_control_interval(fps) if interpolator else 1 / fps
    # Pre-compute action key order outside the hot loop — it won't change mid-episode.
    action_keys = sorted(robot.action_features) if use_interpolation else []

    no_action_count = 0
    timestamp = 0
    start_episode_t = time.perf_counter()

    # Rolling-window state for the "loop running slower than target FPS"
    # warning. See the warn block below; we suppress per-iteration blips
    # (every n_action_steps frames a chunk-renewal inference takes 200-1000
    # ms, which is fine if the average throughput keeps up) and only warn
    # when the average over the last ``_warn_window`` iters drops below
    # target. ``_last_slow_warn_t`` is a 1-element list so we can mutate
    # it from inside the loop without ``nonlocal``.
    _warn_window: int = max(2 * fps, 30)
    _slow_iter_history: list[float] = []
    _last_slow_warn_t: list[float] = [0.0]

    # Debug-print the first N policy iterations: dumps observation.state,
    # commanded action, and per-joint delta so we can see exactly what the
    # policy is doing when the arms appear to move unexpectedly (e.g.
    # "dropped right after lift_arms"). Counter resets each episode.
    debug_actions_remaining = int(debug_first_actions) if policy is not None else 0
    # Counter for "log on each fresh inference" mode; lets us see one log
    # line per chunk, which reveals long-horizon drift of the model's
    # intent (something debug_first_actions misses if N < chunk_size).
    debug_inference_remaining = int(debug_log_each_inference) if policy is not None else 0
    debug_inference_idx = 0
    # Optional: dump the EXACT observation the policy sees (state + camera
    # images) on the first N fresh inferences, gated by env var so it needs no
    # CLI plumbing. These .npz files are then replayed offline through BOTH the
    # openpi server and the lerobot policy (scripts/diag_ab_openpi_vs_lerobot.py
    # --captured-frame) to prove whether live camera frames are the reason the
    # arms drift up while openpi works on the same rig.
    #   LEROBOT_DUMP_OBS_DIR=/path   (enables capture)
    #   LEROBOT_DUMP_OBS_N=5         (how many fresh-inference frames, default 5)
    obs_dump_dir = os.environ.get("LEROBOT_DUMP_OBS_DIR") if policy is not None else None
    obs_dump_remaining = int(os.environ.get("LEROBOT_DUMP_OBS_N", "5")) if obs_dump_dir else 0
    obs_dump_idx = 0
    if obs_dump_dir:
        Path(obs_dump_dir).mkdir(parents=True, exist_ok=True)
        logging.info("[dump_obs] will save first %d fresh-inference observations to %s",
                     obs_dump_remaining, obs_dump_dir)

    # Optional: drive the robot live from an openpi websocket policy server
    # instead of the local lerobot policy. Gated by env var so it needs no CLI
    # plumbing and is a no-op when unset.
    #   LEROBOT_OPENPI_SERVER=localhost:8002
    # Camera name mapping (lerobot stream -> openpi server key) matches the
    # SparkJAX/openpi training convention.
    openpi_driver = None
    _openpi_server = os.environ.get("LEROBOT_OPENPI_SERVER") if policy is not None else None
    if _openpi_server:
        _host, _, _port = _openpi_server.partition(":")
        openpi_driver = OpenPIServerPolicy(
            host=_host or "localhost",
            port=int(_port or "8002"),
            image_key_map={"ego": "cam_high",
                           "left_wrist": "cam_left_wrist",
                           "right_wrist": "cam_right_wrist"},
        )
        logging.warning(
            "[openpi-live] DRIVING ROBOT FROM OPENPI SERVER %s (local lerobot "
            "policy is loaded but its actions are IGNORED).", _openpi_server,
        )
    debug_joint_order = (
        "left_joint_1", "left_joint_2", "left_joint_3", "left_joint_4",
        "left_joint_5", "left_joint_6", "left_joint_7", "left_gripper",
        "right_joint_1", "right_joint_2", "right_joint_3", "right_joint_4",
        "right_joint_5", "right_joint_6", "right_joint_7", "right_gripper",
    )

    # Profiling state (only used when profile_loop=True). We track per-phase
    # latencies plus an "inference vs queue-pop" classifier (heuristic: any
    # predict_action call > 100 ms must have actually run the chunk
    # inference; anything under that is amortised queue pop / preproc).
    prof_phase: dict[str, list[float]] = {"obs": [], "predict": [], "send": [], "total": []}
    prof_inference_ms: list[float] = []
    prof_queue_pop_ms: list[float] = []
    prof_iter_count = 0
    prof_last_log_t = time.perf_counter()
    if profile_loop and policy is not None:
        try:
            param_device = next(policy.parameters()).device
            param_dtype = next(policy.parameters()).dtype
        except StopIteration:
            param_device = "unknown"
            param_dtype = "unknown"
        logging.info(
            "[profile_loop] policy device=%s dtype=%s | torch.cuda.is_available()=%s | "
            "configured device=%s | use_amp=%s",
            param_device,
            param_dtype,
            torch.cuda.is_available(),
            getattr(policy.config, "device", "?"),
            getattr(policy.config, "use_amp", "?"),
        )
        n_action_steps = getattr(policy.config, "n_action_steps", None)
        chunk_size = getattr(policy.config, "chunk_size", None)
        logging.info(
            "[profile_loop] policy chunk_size=%s n_action_steps=%s "
            "(predict_action runs full inference once every n_action_steps calls)",
            chunk_size,
            n_action_steps,
        )

    while timestamp < control_time_s:
        start_loop_t = time.perf_counter()

        if events["exit_early"]:
            events["exit_early"] = False
            break

        # Get robot observation
        t_obs_start = time.perf_counter()
        obs = robot.get_observation()
        t_obs_end = time.perf_counter()

        # Applies a pipeline to the raw robot observation, default is IdentityProcessor
        obs_processed = robot_observation_processor(obs)

        if policy is not None or dataset is not None:
            observation_frame = build_dataset_frame(dataset.features, obs_processed, prefix=OBS_STR)

        # Track whether this iteration should be recorded to the dataset.
        # Interpolated-only iterations send actions to the robot but don't record frames,
        # keeping the dataset at the original fps while the robot moves at the higher rate.
        is_record_frame = True

        # Get action from either policy or teleop
        t_predict_ms = 0.0
        if policy is not None and preprocessor is not None and postprocessor is not None:
            # With interpolation: only call policy when interpolator needs new action
            if use_interpolation:
                ran_inference = False

                if interpolator.needs_new_action():
                    t_predict_start = time.perf_counter()
                    action_values = predict_action(
                        observation=observation_frame,
                        policy=policy,
                        device=get_safe_torch_device(policy.config.device),
                        preprocessor=preprocessor,
                        postprocessor=postprocessor,
                        use_amp=policy.config.use_amp,
                        task=single_task,
                        robot_type=robot.robot_type,
                    )
                    t_predict_ms = (time.perf_counter() - t_predict_start) * 1000.0
                    act_processed_policy = make_robot_action(action_values, dataset.features)
                    robot_action_to_send = robot_action_processor((act_processed_policy, obs))

                    action_tensor = torch.tensor([robot_action_to_send[k] for k in action_keys])
                    interpolator.add(action_tensor)
                    ran_inference = True

                interp_action = interpolator.get()
                if interp_action is not None:
                    robot_action_to_send = {k: interp_action[i].item() for i, k in enumerate(action_keys)}
                    action_values = robot_action_to_send
                else:
                    continue

                is_record_frame = ran_inference
            elif openpi_driver is not None:
                t_predict_start = time.perf_counter()
                action_values = openpi_driver.predict(observation_frame, single_task)
                t_predict_ms = (time.perf_counter() - t_predict_start) * 1000.0
                act_processed_openpi = make_robot_action(action_values, dataset.features)
                robot_action_to_send = robot_action_processor((act_processed_openpi, obs))
                action_values = robot_action_to_send
            else:
                t_predict_start = time.perf_counter()
                action_values = predict_action(
                    observation=observation_frame,
                    policy=policy,
                    device=get_safe_torch_device(policy.config.device),
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    use_amp=policy.config.use_amp,
                    task=single_task,
                    robot_type=robot.robot_type,
                )
                t_predict_ms = (time.perf_counter() - t_predict_start) * 1000.0
                act_processed_policy: RobotAction = make_robot_action(action_values, dataset.features)
                # Applies a pipeline to the action, default is IdentityProcessor
                robot_action_to_send = robot_action_processor((act_processed_policy, obs))
                action_values = robot_action_to_send

        elif policy is None and isinstance(teleop, Teleoperator):
            act = teleop.get_action()
            if robot.name == "unitree_g1":
                teleop.send_feedback(obs)

            # Applies a pipeline to the raw teleop action, default is IdentityProcessor
            act_processed_teleop = teleop_action_processor((act, obs))
            action_values = act_processed_teleop
            robot_action_to_send = robot_action_processor((act_processed_teleop, obs))

        elif policy is None and isinstance(teleop, list):
            arm_action = teleop_arm.get_action()
            arm_action = {f"arm_{k}": v for k, v in arm_action.items()}
            keyboard_action = teleop_keyboard.get_action()
            base_action = robot._from_keyboard_to_base_action(keyboard_action)
            act = {**arm_action, **base_action} if len(base_action) > 0 else arm_action
            act_processed_teleop = teleop_action_processor((act, obs))
            action_values = act_processed_teleop
            robot_action_to_send = robot_action_processor((act_processed_teleop, obs))
        else:
            no_action_count += 1
            if no_action_count == 1 or no_action_count % 10 == 0:
                logging.warning(
                    "No policy or teleoperator provided, skipping action generation. "
                    "This is likely to happen when resetting the environment without a teleop device. "
                    "The robot won't be at its rest position at the start of the next episode."
                )
            continue

        # Hard-abort safety gate. Only runs when a policy is producing the
        # action (teleop is trusted to be human-driven). Three gates: NaN/Inf,
        # absolute envelope, per-step delta. On violation: send the last good
        # action as an explicit hold frame, then raise — the outer try/finally
        # disconnects the robot and (by default) disables torque.
        if action_safety is not None and policy is not None:
            safety_err = action_safety.check(robot_action_to_send, obs)
            if safety_err is not None:
                logging.error("[POLICY-ABORT] %s", safety_err)
                if action_safety.last_action is not None:
                    try:
                        robot.send_action(action_safety.last_action)
                    except Exception:
                        logging.exception("Failed to send hold-pose frame after safety abort")
                raise ActionSafetyViolation(safety_err)

        # Debug: dump first N policy iterations so we can see what the model
        # actually commands relative to the current observation. Helps
        # diagnose "arms behave oddly right after lift_arms" failures.
        if debug_actions_remaining > 0 and policy is not None:
            try:
                def _fmt(name: str) -> str:
                    key = f"{name}.pos"
                    s = obs.get(key)
                    a = robot_action_to_send.get(key)
                    if s is None or a is None:
                        return f"{name}=<missing>"
                    return f"{name}: s={s:+7.2f} a={a:+7.2f} d={a - s:+6.2f}"
                left = "  ".join(_fmt(n) for n in debug_joint_order[:8])
                right = "  ".join(_fmt(n) for n in debug_joint_order[8:])
                logging.info(
                    "[debug_first_actions] iter=%d (deg, s=state a=action d=delta)\n"
                    "  L: %s\n  R: %s",
                    int(debug_first_actions) - debug_actions_remaining + 1,
                    left, right,
                )
            except Exception:
                logging.exception("[debug_first_actions] dump failed")
            debug_actions_remaining -= 1

        # Per-chunk debug: log the model's "first action of the chunk" on
        # every iteration where fresh inference actually ran (heuristic:
        # predict time > 100 ms, same threshold profile_loop uses). For
        # chunk-based policies this gives you one line per chunk, ~every
        # 1.6 s at chunk_size=50, fps=30. Useful for spotting long-horizon
        # drift in the model's intent (e.g. arms slowly moving down means
        # each new chunk targets a lower pose, even if individual chunks
        # look like "hold").
        if (
            debug_inference_remaining > 0
            and policy is not None
            and t_predict_ms > 100.0
        ):
            try:
                def _fmt_inf(name: str) -> str:
                    key = f"{name}.pos"
                    s = obs.get(key)
                    a = robot_action_to_send.get(key)
                    if s is None or a is None:
                        return f"{name}=<missing>"
                    return f"{name}: s={s:+7.2f} a={a:+7.2f} d={a - s:+6.2f}"
                left = "  ".join(_fmt_inf(n) for n in debug_joint_order[:8])
                right = "  ".join(_fmt_inf(n) for n in debug_joint_order[8:])
                debug_inference_idx += 1
                logging.info(
                    "[debug_log_each_inference] inf=%d (t_predict=%.0fms, deg, s=state a=action[0_of_chunk] d=delta)\n"
                    "  L: %s\n  R: %s",
                    debug_inference_idx,
                    t_predict_ms,
                    left, right,
                )
            except Exception:
                logging.exception("[debug_log_each_inference] dump failed")
            debug_inference_remaining -= 1

        # Capture the exact observation fed to the policy on fresh-inference
        # frames, so it can be replayed offline through openpi + lerobot.
        if (
            obs_dump_remaining > 0
            and policy is not None
            and t_predict_ms > 100.0
            and observation_frame is not None
        ):
            try:
                payload: dict[str, np.ndarray] = {}
                for k, v in observation_frame.items():
                    arr = v.cpu().numpy() if isinstance(v, torch.Tensor) else np.asarray(v)
                    payload[k] = arr
                # Also stash the commanded action[0] (degrees, wire format) and
                # the task string so the offline replay is fully self-contained.
                act_keys = sorted(robot_action_to_send.keys())
                payload["_action0_wire"] = np.asarray(
                    [robot_action_to_send[k] for k in act_keys], dtype=np.float32,
                )
                payload["_action0_keys"] = np.array(act_keys)
                task_str = single_task if isinstance(single_task, str) else ""
                out_path = Path(obs_dump_dir) / f"frame_{obs_dump_idx:03d}.npz"
                np.savez_compressed(out_path, task=np.array(task_str), **payload)
                logging.info("[dump_obs] saved %s (keys=%s)",
                             out_path.name, list(payload.keys()))
                obs_dump_idx += 1
            except Exception:
                logging.exception("[dump_obs] capture failed")
            obs_dump_remaining -= 1

        # Send action to robot
        # Action can eventually be clipped using `max_relative_target`,
        # so action actually sent is saved in the dataset. action = postprocessor.process(action)
        # TODO(steven, pepijn, adil): we should use a pipeline step to clip the action, so the sent action is the action that we input to the robot.
        t_send_start = time.perf_counter()
        _sent_action = robot.send_action(robot_action_to_send)
        t_send_ms = (time.perf_counter() - t_send_start) * 1000.0

        # Write to dataset (only on real policy frames, not interpolated-only iterations)
        if dataset is not None and is_record_frame:
            action_frame = build_dataset_frame(dataset.features, action_values, prefix=ACTION)
            frame = {**observation_frame, **action_frame, "task": single_task}
            dataset.add_frame(frame)

        if display_data:
            log_rerun_data(
                observation=obs_processed, action=action_values, compress_images=display_compressed_images
            )

        dt_s = time.perf_counter() - start_loop_t

        if profile_loop:
            obs_ms = (t_obs_end - t_obs_start) * 1000.0
            total_ms = dt_s * 1000.0
            prof_phase["obs"].append(obs_ms)
            prof_phase["predict"].append(t_predict_ms)
            prof_phase["send"].append(t_send_ms)
            prof_phase["total"].append(total_ms)
            if t_predict_ms > 100.0:
                prof_inference_ms.append(t_predict_ms)
            elif t_predict_ms > 0.0:
                prof_queue_pop_ms.append(t_predict_ms)
            prof_iter_count += 1

            if time.perf_counter() - prof_last_log_t >= profile_log_period_s:
                def _pct(xs: list[float], q: float) -> float:
                    if not xs:
                        return 0.0
                    s = sorted(xs)
                    idx = min(len(s) - 1, max(0, int(round(q * (len(s) - 1)))))
                    return s[idx]

                n_inf = len(prof_inference_ms)
                n_pop = len(prof_queue_pop_ms)
                logging.info(
                    "[profile_loop] iters=%d  loop_hz=%.1f  "
                    "obs(med=%.1f p95=%.1f) ms  "
                    "predict(med=%.1f p95=%.1f) ms  "
                    "send(med=%.1f p95=%.1f) ms  "
                    "inference(n=%d med=%.0f max=%.0f) ms  "
                    "queue_pop(n=%d med=%.1f) ms",
                    prof_iter_count,
                    1000.0 / max(_pct(prof_phase["total"], 0.5), 1e-3),
                    _pct(prof_phase["obs"], 0.5), _pct(prof_phase["obs"], 0.95),
                    _pct(prof_phase["predict"], 0.5), _pct(prof_phase["predict"], 0.95),
                    _pct(prof_phase["send"], 0.5), _pct(prof_phase["send"], 0.95),
                    n_inf, _pct(prof_inference_ms, 0.5),
                    (max(prof_inference_ms) if prof_inference_ms else 0.0),
                    n_pop, _pct(prof_queue_pop_ms, 0.5),
                )
                for k in prof_phase:
                    prof_phase[k].clear()
                prof_inference_ms.clear()
                prof_queue_pop_ms.clear()
                prof_iter_count = 0
                prof_last_log_t = time.perf_counter()

        sleep_time_s: float = control_interval - dt_s
        if sleep_time_s < 0:
            # A single slow iteration is expected every ``n_action_steps``
            # frames when the chunk runner has to call full inference (200-
            # 1000 ms for pi05 on consumer GPUs). What we actually care
            # about is whether the AVERAGE throughput is below the target -
            # if so, frames will be dropped and the robot will lag the
            # policy. Track the most recent ``warn_window`` iterations and
            # warn only when their summed elapsed time exceeds the budget
            # for that many iterations. This suppresses the per-inference
            # blip and only catches real sustained slowdown.
            _slow_iter_history.append(dt_s)
            if len(_slow_iter_history) > _warn_window:
                _slow_iter_history.pop(0)
            if len(_slow_iter_history) == _warn_window:
                window_dt = sum(_slow_iter_history)
                budget = control_interval * _warn_window
                if window_dt > budget * 1.05:  # 5 % slack
                    avg_hz = _warn_window / window_dt
                    now = time.perf_counter()
                    if now - _last_slow_warn_t[0] >= 5.0:
                        logging.warning(
                            "Record loop sustained avg %.1f Hz over last %d iters "
                            "(target FPS %d). Dataset frames will be dropped and "
                            "robot control may be unstable. Common causes: "
                            "1) camera FPS not keeping up 2) policy inference "
                            "too slow 3) CPU starvation.",
                            avg_hz, _warn_window, fps,
                        )
                        _last_slow_warn_t[0] = now

        precise_sleep(max(sleep_time_s, 0.0))

        timestamp = time.perf_counter() - start_episode_t


@parser.wrap()
def record(cfg: RecordConfig) -> LeRobotDataset:
    init_logging()
    logging.info(pformat(asdict(cfg)))
    if cfg.display_data:
        init_rerun(session_name="recording", ip=cfg.display_ip, port=cfg.display_port)
    display_compressed_images = (
        True
        if (cfg.display_data and cfg.display_ip is not None and cfg.display_port is not None)
        else cfg.display_compressed_images
    )

    robot = make_robot_from_config(cfg.robot)
    teleop = make_teleoperator_from_config(cfg.teleop) if cfg.teleop is not None else None

    teleop_action_processor, robot_action_processor, robot_observation_processor = make_default_processors()

    dataset_features = combine_feature_dicts(
        aggregate_pipeline_dataset_features(
            pipeline=teleop_action_processor,
            initial_features=create_initial_features(
                action=robot.action_features
            ),  # TODO(steven, pepijn): in future this should be come from teleop or policy
            use_videos=cfg.dataset.video,
        ),
        aggregate_pipeline_dataset_features(
            pipeline=robot_observation_processor,
            initial_features=create_initial_features(observation=robot.observation_features),
            use_videos=cfg.dataset.video,
        ),
    )

    dataset = None
    listener = None

    try:
        if cfg.resume:
            num_cameras = len(robot.cameras) if hasattr(robot, "cameras") else 0
            dataset = LeRobotDataset.resume(
                cfg.dataset.repo_id,
                root=cfg.dataset.root,
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
                streaming_encoding=cfg.dataset.streaming_encoding,
                encoder_queue_maxsize=cfg.dataset.encoder_queue_maxsize,
                encoder_threads=cfg.dataset.encoder_threads,
                image_writer_processes=cfg.dataset.num_image_writer_processes if num_cameras > 0 else 0,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * num_cameras
                if num_cameras > 0
                else 0,
            )
            sanity_check_dataset_robot_compatibility(dataset, robot, cfg.dataset.fps, dataset_features)
        else:
            # Create empty dataset or load existing saved episodes
            sanity_check_dataset_name(cfg.dataset.repo_id, cfg.policy)
            dataset = LeRobotDataset.create(
                cfg.dataset.repo_id,
                cfg.dataset.fps,
                root=cfg.dataset.root,
                robot_type=robot.name,
                features=dataset_features,
                use_videos=cfg.dataset.video,
                image_writer_processes=cfg.dataset.num_image_writer_processes,
                image_writer_threads=cfg.dataset.num_image_writer_threads_per_camera * len(robot.cameras),
                batch_encoding_size=cfg.dataset.video_encoding_batch_size,
                vcodec=cfg.dataset.vcodec,
                streaming_encoding=cfg.dataset.streaming_encoding,
                encoder_queue_maxsize=cfg.dataset.encoder_queue_maxsize,
                encoder_threads=cfg.dataset.encoder_threads,
            )

        # Load pretrained policy
        policy = None if cfg.policy is None else make_policy(cfg.policy, ds_meta=dataset.meta)
        preprocessor = None
        postprocessor = None
        interpolator = None
        if cfg.policy is not None:
            preprocessor, postprocessor = make_pre_post_processors(
                policy_cfg=cfg.policy,
                pretrained_path=cfg.policy.pretrained_path,
                dataset_stats=rename_stats(dataset.meta.stats, cfg.dataset.rename_map),
                preprocessor_overrides={
                    "device_processor": {"device": cfg.policy.device},
                    "rename_observations_processor": {"rename_map": cfg.dataset.rename_map},
                },
            )
            # Create interpolator for smoother policy control
            if cfg.interpolation_multiplier > 1:
                interpolator = ActionInterpolator(multiplier=cfg.interpolation_multiplier)
                logging.info(f"Action interpolation enabled: {cfg.interpolation_multiplier}x control rate")

        robot.connect()
        if teleop is not None:
            teleop.connect()

        # Install an aggressive Ctrl-C handler that disables motor torque
        # IMMEDIATELY on first SIGINT, then re-raises KeyboardInterrupt so the
        # normal try/finally in this function still runs (dataset.finalize,
        # robot.disconnect, etc.). Without this, a Ctrl-C that lands during
        # a long policy.predict_action CUDA call sits queued until the call
        # returns (Python defers signal delivery to interpreter ticks, which
        # don't run inside extension code), so the arms stay torqued for up
        # to ~9 s before any cleanup runs. We also IGNORE subsequent SIGINTs
        # while shutting down so an impatient double-Ctrl-C can't abort the
        # cleanup path itself.
        import signal as _signal

        _sigint_state = {"fired": False, "prev": _signal.getsignal(_signal.SIGINT)}

        def _emergency_disable_torque(*_args: object) -> None:
            if _sigint_state["fired"]:
                # second Ctrl-C: ignore so cleanup runs to completion
                return
            _sigint_state["fired"] = True
            logging.warning("SIGINT received - disabling motor torque NOW.")
            # Try bimanual first (BiOpenArmFollower exposes left_arm/right_arm),
            # fall back to a flat single-arm follower.
            try:
                for arm_attr in ("left_arm", "right_arm"):
                    arm = getattr(robot, arm_attr, None)
                    if arm is not None and getattr(arm, "is_connected", False):
                        try:
                            arm.bus.disable_torque()
                            logging.warning(f"  {arm_attr}: torque disabled")
                        except Exception as e:
                            logging.error(f"  {arm_attr}: failed to disable torque: {e}")
                if not any(getattr(robot, a, None) for a in ("left_arm", "right_arm")):
                    bus = getattr(robot, "bus", None)
                    if bus is not None:
                        try:
                            bus.disable_torque()
                            logging.warning("  bus: torque disabled")
                        except Exception as e:
                            logging.error(f"  bus: failed to disable torque: {e}")
            except Exception as e:
                logging.error(f"SIGINT torque-disable handler error: {e}")
            # ignore further SIGINTs until cleanup completes
            _signal.signal(_signal.SIGINT, _signal.SIG_IGN)
            # raise KeyboardInterrupt synchronously so the outer try/finally runs
            raise KeyboardInterrupt

        _signal.signal(_signal.SIGINT, _emergency_disable_torque)

        # Build the policy-action safety guard. Always None when no policy is
        # loaded; otherwise None if the user opts out via --action_safety_enabled=false.
        # Construct once (outside the per-episode loop) so an abort stays sticky
        # across the rest of the session.
        action_safety: ActionSafetyChecker | None = None
        if policy is not None and cfg.action_safety_enabled:
            action_safety = ActionSafetyChecker(
                ActionSafetyConfig(
                    enabled=True,
                    max_joint_delta_deg=cfg.action_safety_max_joint_delta_deg,
                    max_gripper_delta_deg=cfg.action_safety_max_gripper_delta_deg,
                    abs_joint_limit_deg=cfg.action_safety_abs_joint_limit_deg,
                    abs_gripper_limit_deg=cfg.action_safety_abs_gripper_limit_deg,
                )
            )
            logging.info(
                "Action safety enabled: max_joint_delta=%.2f deg/step, "
                "max_gripper_delta=%.2f deg/step, abs_joint=±%.1f deg, abs_gripper=±%.1f deg",
                cfg.action_safety_max_joint_delta_deg,
                cfg.action_safety_max_gripper_delta_deg,
                cfg.action_safety_abs_joint_limit_deg,
                cfg.action_safety_abs_gripper_limit_deg,
            )

        if cfg.lift_arms_before_policy and policy is not None:
            from lerobot.robots.bi_openarm_follower import (
                BiOpenArmFollower,
                lift_arms_to_ready,
            )

            if isinstance(robot, BiOpenArmFollower):
                log_say("Raising arms to ready pose", cfg.play_sounds)
                lift_arms_to_ready(
                    robot,
                    pre_zero_s=cfg.lift_arms_pre_zero_s,
                    pre_ramp_s=cfg.lift_arms_pre_ramp_s,
                    spine_duration_s=cfg.lift_arms_spine_s,
                    hz=cfg.lift_arms_hz,
                    hold_s=cfg.lift_arms_hold_s,
                    log_fn=logging.info,
                )
            else:
                logging.warning(
                    "lift_arms_before_policy=True but robot is %s, not BiOpenArmFollower; skipping.",
                    type(robot).__name__,
                )

        listener, events = init_keyboard_listener()

        if not cfg.dataset.streaming_encoding:
            logging.info(
                "Streaming encoding is disabled. If you have capable hardware, consider enabling it for way faster episode saving. --dataset.streaming_encoding=true --dataset.encoder_threads=2 # --dataset.vcodec=auto. More info in the documentation: https://huggingface.co/docs/lerobot/streaming_video_encoding"
            )

        with VideoEncodingManager(dataset):
            recorded_episodes = 0
            while recorded_episodes < cfg.dataset.num_episodes and not events["stop_recording"]:
                log_say(f"Recording episode {dataset.num_episodes}", cfg.play_sounds)
                record_loop(
                    robot=robot,
                    events=events,
                    fps=cfg.dataset.fps,
                    teleop_action_processor=teleop_action_processor,
                    robot_action_processor=robot_action_processor,
                    robot_observation_processor=robot_observation_processor,
                    teleop=teleop,
                    policy=policy,
                    preprocessor=preprocessor,
                    postprocessor=postprocessor,
                    dataset=dataset,
                    control_time_s=cfg.dataset.episode_time_s,
                    single_task=cfg.dataset.single_task,
                    display_data=cfg.display_data,
                    interpolator=interpolator,
                    display_compressed_images=display_compressed_images,
                    action_safety=action_safety,
                    profile_loop=cfg.profile_loop,
                    profile_log_period_s=cfg.profile_log_period_s,
                    debug_first_actions=cfg.debug_first_actions,
                    debug_log_each_inference=cfg.debug_log_each_inference,
                )

                # Execute a few seconds without recording to give time to manually reset the environment
                # Skip reset for the last episode to be recorded
                if not events["stop_recording"] and (
                    (recorded_episodes < cfg.dataset.num_episodes - 1) or events["rerecord_episode"]
                ):
                    log_say("Reset the environment", cfg.play_sounds)

                    record_loop(
                        robot=robot,
                        events=events,
                        fps=cfg.dataset.fps,
                        teleop_action_processor=teleop_action_processor,
                        robot_action_processor=robot_action_processor,
                        robot_observation_processor=robot_observation_processor,
                        teleop=teleop,
                        control_time_s=cfg.dataset.reset_time_s,
                        single_task=cfg.dataset.single_task,
                        display_data=cfg.display_data,
                        profile_loop=cfg.profile_loop,
                        profile_log_period_s=cfg.profile_log_period_s,
                    )

                if events["rerecord_episode"]:
                    log_say("Re-record episode", cfg.play_sounds)
                    events["rerecord_episode"] = False
                    events["exit_early"] = False
                    dataset.clear_episode_buffer()
                    continue

                dataset.save_episode()
                recorded_episodes += 1
    finally:
        log_say("Stop recording", cfg.play_sounds, blocking=True)

        if dataset:
            dataset.finalize()

        if robot.is_connected:
            robot.disconnect()
        if teleop and teleop.is_connected:
            teleop.disconnect()

        # Restore the original SIGINT handler so subsequent commands in the
        # same process see normal Ctrl-C behavior again. Wrapped in try/except
        # because the emergency handler is only installed AFTER robot.connect();
        # if we faulted before that, _sigint_state never got bound.
        try:
            import signal as _signal
            if "_sigint_state" in locals():
                _signal.signal(_signal.SIGINT, _sigint_state["prev"])  # type: ignore[arg-type]
        except Exception:
            pass

        if not is_headless() and listener:
            listener.stop()

        if cfg.dataset.push_to_hub:
            dataset.push_to_hub(tags=cfg.dataset.tags, private=cfg.dataset.private)

        log_say("Exiting", cfg.play_sounds)
    return dataset


def main():
    register_third_party_plugins()
    record()


if __name__ == "__main__":
    main()
